ALTER TABLE players
ADD COLUMN IF NOT EXISTS wins INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS losses INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_streak INTEGER DEFAULT 0;

ALTER TABLE players DROP COLUMN IF EXISTS is_playing_tetris;
